#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

##start elasticsearch
##nohup $OPENSHIFT_DATA_DIR/elasticsearch/bin/elasticsearch

export HTTP_CLIENT="wget --no-check-certificate -O"
export HTTP_CLIENT="curl --insecure -f -L -o"
export APPDIR="raiseup"
export LEIN_REPL_HOST=$OPENSHIFT_DIY_IP
export PORT=$OPENSHIFT_DIY_PORT
export HOST=$OPENSHIFT_DIY_IP
export HOME=$OPENSHIFT_DATA_DIR/home
export LEIN_JVM_OPTS=-Duser.home=$HOME
export LEIN_REPL_PORT=35000
chmod 755 $OPENSHIFT_REPO_DIR/bin/lein

cd $OPENSHIFT_REPO_DIR/diy/$APPDIR
sh $OPENSHIFT_REPO_DIR/bin/lein clean
sh $OPENSHIFT_REPO_DIR/bin/lein compile

java -server -Dproduction=true -Dconfig=config.pro.clj  -Dhazelcast.local.localAddress=${OPENSHIFT_DIY_IP} -Dhazelcast.socket.bind.any=false -cp `$OPENSHIFT_REPO_DIR/bin/lein classpath` clojure.main -m  main $HOST $PORT > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &

echo $OPENSHIFT_REPO_DIR/diy/$APPDIR "host" $HOST ":" $PORT
disown
echo 'Ring server is started'
