#!/bin/bash
# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#exit 0
kill `ps -ef | grep 'clojure' | grep -v 'grep clojure' | awk '{ print $2  }'` >${OPENSHIFT_DIY_LOG_DIR}/stop.log 2>&1
exit 0
